# Generated by Django 4.1.3 on 2022-11-20 13:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('street', models.CharField(max_length=20, verbose_name='Улица')),
                ('number', models.IntegerField(verbose_name='Номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('treatment', models.CharField(max_length=50, verbose_name='Лечение')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_manufacturer', to='app.address', verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('dosage', models.CharField(max_length=30, verbose_name='Дозировка')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disease', verbose_name='Заболевание')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Форма выпуска')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('state_number', models.CharField(max_length=20, verbose_name='Государственный номер')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_pharmacy', to='app.address', verbose_name='Адрес')),
                ('employee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='дата заявки')),
                ('reason', models.CharField(max_length=100, verbose_name='Основние')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая цена')),
                ('writeoff', models.BooleanField(default=False)),
                ('medicines', models.ManyToManyField(to='app.medicament')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pharmacy', verbose_name='Аптека')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentInPharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('expiration_date', models.DateField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicament', verbose_name='Лекарственное средство')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pharmacy', verbose_name='Аптека')),
            ],
        ),
        migrations.AddField(
            model_name='medicament',
            name='form_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.releaseform', verbose_name='Форма выпуска'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer', verbose_name='Производитель'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, verbose_name='Основние')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая цена')),
                ('medicines', models.ManyToManyField(to='app.medicament')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
            ],
        ),
    ]
