# Generated by Django 4.1.3 on 2022-11-20 15:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentinpharmacy',
            name='expiration_date',
            field=models.DateField(verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='medicamentinpharmacy',
            name='number',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата заявки'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('reason', models.CharField(max_length=100, verbose_name='Основние')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая цена')),
                ('medicines', models.ManyToManyField(to='app.medicamentinpharmacy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
